name: Release

on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test --verbosity normal

      - name: Package
        run: dotnet pack -c Release -p:ContinuousIntegrationBuild=true -o artifacts

      - name: Publish if version has changed
        run: dotnet nuget push "artifacts/*.nupkg" -s https://www.nuget.org -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Publish symbols
        run: dotnet nuget push "artifacts/*.snupkg" -s https://www.nuget.org -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: 'artifacts/*'